name: Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Synchronize configuration to permanent directory
        run: |
          # Копируем свежие версии конфигов из временной папки (_work)
          # в постоянную папку проекта (/opt/apps/relaxy).
          # Флаг --delete удалит старые файлы, если вы их переименовали или удалили.
          sudo rsync -av --delete ${{ github.workspace }}/ /opt/apps/relaxy/ --exclude 'data'

      - name: Deploy services from permanent directory
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          # Переходим в постоянную папку проекта
          cd /opt/apps/relaxy

          # Запускаем docker-compose уже отсюда.
          sudo -E docker compose up -d --build --force-recreate --remove-orphans --wait nginx
