name: Deploy on Push

on:
  push:
    branches:
      - master # Or your default branch, e.g., master

jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Deploy services
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          # Navigate to your project directory on the server
          cd ${{ github.workspace }}

          # Rebuild and restart your services with Docker Compose
          # Environment variables are passed from the 'env' context above
          # We explicitly specify `nginx` to ensure only the proxy server is started on deploy.
          sudo -E docker compose -f docker-compose.yml up -d --build --force-recreate --remove-orphans nginx
